"""initial schema

Revision ID: dbf1a6974ad6
Revises: 
Create Date: 2026-09-17 08:03:38.566306
"""
from alembic import op
import sqlalchemy as sa


revision = 'dbf1a6974ad6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('objective_id', sa.String(length=40), nullable=True),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_objective_id'), ['objective_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_task_id'), ['task_id'], unique=False)

    op.create_table('budget_periods',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('limit_usd', sa.Float(), nullable=False),
    sa.Column('category_limits', sa.JSON(), nullable=False),
    sa.Column('hard_stopped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_periods'))
    )
    with op.batch_alter_table('budget_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_periods_period'), ['period'], unique=True)

    op.create_table('companies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('segment', sa.String(length=80), nullable=True),
    sa.Column('size_indicator', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('buying_signals', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_dedupe_key'), ['dedupe_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_opted_out'), ['opted_out'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_segment'), ['segment'], unique=False)

    op.create_table('compliance_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('opportunity_id', sa.String(length=40), nullable=True),
    sa.Column('product_category', sa.String(length=50), nullable=True),
    sa.Column('flag', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_events'))
    )
    with op.batch_alter_table('compliance_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_events_flag'), ['flag'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_events_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('cost_entries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_entries'))
    )
    with op.batch_alter_table('cost_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_entries_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_entries_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_entries_state'), ['state'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verification', sa.String(length=20), nullable=False),
    sa.Column('subject_type', sa.String(length=40), nullable=True),
    sa.Column('subject_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_subject_type'), ['subject_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_verification'), ['verification'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('strategy_name', sa.String(length=160), nullable=False),
    sa.Column('control_version', sa.Integer(), nullable=False),
    sa.Column('variant_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metric', sa.String(length=60), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_strategy_name'), ['strategy_name'], unique=False)

    op.create_table('market_assessments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('product_category', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_assessments'))
    )
    with op.batch_alter_table('market_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_assessments_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_assessments_product_category'), ['product_category'], unique=False)

    op.create_table('model_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_runs'))
    )
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_runs_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_runs_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_runs_tier'), ['tier'], unique=False)

    op.create_table('objectives',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_objectives'))
    )
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objectives_status'), ['status'], unique=False)

    op.create_table('scheduled_jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=30), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_jobs'))
    )
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_jobs_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_scheduled_jobs_next_run_at'), ['next_run_at'], unique=False)

    op.create_table('strategies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies')),
    sa.UniqueConstraint('name', 'version', name='uq_strategies_name_version')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategies_name'), ['name'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('payment_terms', sa.String(length=160), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_dedupe_key'), ['dedupe_key'], unique=True)

    op.create_table('system_state',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_state'))
    )
    op.create_table('buyer_requirements',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.String(length=40), nullable=False),
    sa.Column('product_category', sa.String(length=50), nullable=False),
    sa.Column('specification', sa.JSON(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('target_price_usd', sa.Float(), nullable=True),
    sa.Column('timing', sa.String(length=120), nullable=True),
    sa.Column('evidence_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_buyer_requirements_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buyer_requirements'))
    )
    with op.batch_alter_table('buyer_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buyer_requirements_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buyer_requirements_product_category'), ['product_category'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_id', sa.String(length=40), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bounced', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_contacts_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_opted_out'), ['opted_out'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('condition', sa.String(length=60), nullable=True),
    sa.Column('specification', sa.JSON(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=True),
    sa.Column('acquisition_cost_usd', sa.Float(), nullable=True),
    sa.Column('target_price_usd', sa.Float(), nullable=True),
    sa.Column('minimum_margin_pct', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('supplier_id', sa.String(length=40), nullable=True),
    sa.Column('warranty', sa.String(length=160), nullable=True),
    sa.Column('shipping_terms', sa.String(length=160), nullable=True),
    sa.Column('payment_terms', sa.String(length=160), nullable=True),
    sa.Column('regulatory', sa.JSON(), nullable=False),
    sa.Column('documentation', sa.JSON(), nullable=False),
    sa.Column('availability', sa.String(length=60), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_products_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('objective_id', sa.String(length=40), nullable=True),
    sa.Column('parent_id', sa.String(length=40), nullable=True),
    sa.Column('agent', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], name=op.f('fk_tasks_objective_id_objectives')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('idempotency_key', name='uq_tasks_idempotency_key')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_objective_id'), ['objective_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('opportunities',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('objective_id', sa.String(length=40), nullable=True),
    sa.Column('company_id', sa.String(length=40), nullable=False),
    sa.Column('contact_id', sa.String(length=40), nullable=True),
    sa.Column('product_category', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('qualification', sa.JSON(), nullable=False),
    sa.Column('economics', sa.JSON(), nullable=False),
    sa.Column('supplier_id', sa.String(length=40), nullable=True),
    sa.Column('estimated_value_usd', sa.Float(), nullable=True),
    sa.Column('estimated_margin_usd', sa.Float(), nullable=True),
    sa.Column('compliance_flags', sa.JSON(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_opportunities_company_id_companies')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_opportunities_contact_id_contacts')),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], name=op.f('fk_opportunities_objective_id_objectives')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_opportunities_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities'))
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_dedupe_key'), ['dedupe_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_opportunities_objective_id'), ['objective_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_product_category'), ['product_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_stage'), ['stage'], unique=False)

    op.create_table('follow_ups',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('opportunity_id', sa.String(length=40), nullable=False),
    sa.Column('contact_id', sa.String(length=40), nullable=True),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stop_reason', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_follow_ups_contact_id_contacts')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_follow_ups_opportunity_id_opportunities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow_ups'))
    )
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_ups_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_status'), ['status'], unique=False)

    op.create_table('interactions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('opportunity_id', sa.String(length=40), nullable=True),
    sa.Column('company_id', sa.String(length=40), nullable=True),
    sa.Column('contact_id', sa.String(length=40), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_interactions_company_id_companies')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_interactions_contact_id_contacts')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_interactions_opportunity_id_opportunities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactions'))
    )
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('opportunity_id', sa.String(length=40), nullable=True),
    sa.Column('contact_id', sa.String(length=40), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sequence_step', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('provider_message_id', sa.String(length=120), nullable=True),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('fact_check', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_messages_contact_id_contacts')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_messages_opportunity_id_opportunities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index('ix_messages_dedupe_direction', ['dedupe_key', 'direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_status'), ['status'], unique=False)

    op.create_table('outcomes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('opportunity_id', sa.String(length=40), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('revenue_usd', sa.Float(), nullable=True),
    sa.Column('margin_usd', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('strategy_id', sa.String(length=40), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_outcomes_opportunity_id_opportunities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcomes'))
    )
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcomes_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcomes_result'), ['result'], unique=False)

    op.create_table('stage_transitions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('opportunity_id', sa.String(length=40), nullable=False),
    sa.Column('from_stage', sa.String(length=30), nullable=True),
    sa.Column('to_stage', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_stage_transitions_opportunity_id_opportunities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_transitions'))
    )
    with op.batch_alter_table('stage_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_transitions_opportunity_id'), ['opportunity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stage_transitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_transitions_opportunity_id'))

    op.drop_table('stage_transitions')
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcomes_result'))
        batch_op.drop_index(batch_op.f('ix_outcomes_opportunity_id'))

    op.drop_table('outcomes')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_status'))
        batch_op.drop_index(batch_op.f('ix_messages_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_messages_direction'))
        batch_op.drop_index(batch_op.f('ix_messages_dedupe_key'))
        batch_op.drop_index('ix_messages_dedupe_direction')
        batch_op.drop_index(batch_op.f('ix_messages_contact_id'))

    op.drop_table('messages')
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_company_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_category'))

    op.drop_table('interactions')
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_ups_status'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_due_at'))

    op.drop_table('follow_ups')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_stage'))
        batch_op.drop_index(batch_op.f('ix_opportunities_product_category'))
        batch_op.drop_index(batch_op.f('ix_opportunities_objective_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_opportunities_company_id'))

    op.drop_table('opportunities')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_parent_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_objective_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_tasks_agent'))

    op.drop_table('tasks')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_category'))

    op.drop_table('products')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_opted_out'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_contacts_company_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('buyer_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buyer_requirements_product_category'))
        batch_op.drop_index(batch_op.f('ix_buyer_requirements_company_id'))

    op.drop_table('buyer_requirements')
    op.drop_table('system_state')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_dedupe_key'))

    op.drop_table('suppliers')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_name'))
        batch_op.drop_index(batch_op.f('ix_strategies_active'))

    op.drop_table('strategies')
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_jobs_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_scheduled_jobs_name'))

    op.drop_table('scheduled_jobs')
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objectives_status'))

    op.drop_table('objectives')
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_runs_tier'))
        batch_op.drop_index(batch_op.f('ix_model_runs_task_type'))
        batch_op.drop_index(batch_op.f('ix_model_runs_provider'))

    op.drop_table('model_runs')
    with op.batch_alter_table('market_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_assessments_product_category'))
        batch_op.drop_index(batch_op.f('ix_market_assessments_country'))

    op.drop_table('market_assessments')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_strategy_name'))
        batch_op.drop_index(batch_op.f('ix_experiments_status'))

    op.drop_table('experiments')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_verification'))
        batch_op.drop_index(batch_op.f('ix_evidence_subject_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_subject_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_kind'))

    op.drop_table('evidence')
    with op.batch_alter_table('cost_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_entries_state'))
        batch_op.drop_index(batch_op.f('ix_cost_entries_period'))
        batch_op.drop_index(batch_op.f('ix_cost_entries_category'))

    op.drop_table('cost_entries')
    with op.batch_alter_table('compliance_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_events_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_events_flag'))

    op.drop_table('compliance_events')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_segment'))
        batch_op.drop_index(batch_op.f('ix_companies_opted_out'))
        batch_op.drop_index(batch_op.f('ix_companies_domain'))
        batch_op.drop_index(batch_op.f('ix_companies_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_companies_country'))

    op.drop_table('companies')
    with op.batch_alter_table('budget_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_periods_period'))

    op.drop_table('budget_periods')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_task_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_objective_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_decision'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
