#!/usr/bin/env python3
"""Print fresh random secrets for .env. Run once:  python3 scripts/generate_secrets.py >> .env"""

import secrets

print("\n# --- generated by scripts/generate_secrets.py ---")
print(f"POSTGRES_PASSWORD={secrets.token_urlsafe(24)}")
print(f"UNSUBSCRIBE_SECRET={secrets.token_urlsafe(32)}")
print(f"DASHBOARD_PASSWORD={secrets.token_urlsafe(18)}")
